export const drop_data = {
    'Term': [
        '', '6 Months', ' 1 Year'
    ],
    'TPCITerm': [
            '', ' 1 year'
    ],
    'EntityType': [
        '', 'Select Entity Type', 'Individual', 'Corporation', 'Joint Venture', 'Partnership', 'LLC', 'Other'
    ],
    'Liability': [
        '', '$100,000', '$300,000', '$500,000', '$600,000', '$750,000', '$1,000,000'
    ],
    'UMBI': [
        '', 'Select UMBI', 'Declined', '$100,000'
    ],
    'MedicalPayment': [
        '', 'No Coverage', '$1,000', '$2,000', '$5,000'
    ],
    'SpecifiedPerlisdeductible': [
        '', 'Select Specified Perlis deductible', 'No Coverage', '$250', '$500', '$1,000', '$2,500', '$5,000'
    ],
    'Collisiondeductible': [
        '',  'No Coverage', '$250', '$500', '$1,000', '$2,500', '$5,000'
    ],
    'NonOwnedauto': [
        '', 'No', 'Yes'
    ],
    'TowingAndStorage': [
        '', 'No Coverage', '$5,000', '$10,000'
    ],
    'Make': [
        '', 'Select Make', 'ACE', 'ACURA', 'ALCOUGHTLINER', 'ALFA ROMEO', 'ALIKAN', 'ALLCO', 'ALLIS', 'ALLOY', 'ALTEC', 'ALUMATEC',
        'ALUMINUM CUSTOM', 'AMC', 'AMERICAN', 'ANJ', 'APACHE', 'APPLE', 'ART', 'ASPEN', 'ASSEMBLY TRAILER', 'ASVE', 'ATI', 'ATM', 'AUDI', 'AUTOCAR',
        'AZMFG', 'AZTEC', 'BANKS', 'BARRETT', 'BEACHCOMBER', 'BEALL', 'BEAT', 'BEAVER', 'BELSHE', 'BEMCO', 'BENSON', 'BERING', 'BIG TEX', 'BILTRITE',
        'BLACK DIAMOND', 'BMW', 'BOLE', 'BOYDS', 'BOYER', 'BOYSTON', 'BRAGG', 'BRAVO', 'BRAZOS', 'BRE', 'BROCKWAY', 'BROOKFIELD', 'BROWN', 'BRUCE', 'BRUTE',
        'BUBKO', 'BUDD', 'BUGATTI', 'BUICK', "BURMINGHAM", "BUTLER", "BUTTERWORTH", "BW", "C &amp; C", "CACHANILLA", "CADILLAC", "CAL", "CALCR",
        "CAPACITY", "CAPRI", "CAR HAULER", "CARGO", "CARRIER", "CARRYALL", "CARSON", "CASE", "CATERPILLAR", "CENTRAL", "CENTURY", "CHALLENGER", "CHAMPION", "CHAPPERAL",
        "CHASE", "CHASSIS", "CHEROKEE", "CHEVROLET", "CHEYENNE", "CHIEF", "CHISOLM", "CHRYSLER", "CIMC", "CIMLINE", "CIRCL", "CIRCLE R", "CLARENCE", "CLARK", "CLEMENT", "CLEMENTS", "CLOUGH-CLOUG", "CMC", "CMI", "COACHMAN", "COLUMBIA", "COMET", "COMET", "COMMANDER", "COMMERCIAL", "CONSTRUCTION", "CONTINENTAL", "CONTRAIL", "COOK", "CORN", "COTTRELL", "COULSON", "COULTER", "COUNTRYSIDE", "COXS", "COZAD", "CPCNS", "CPS", "CRAFTMADE", "CTS", "CTS", "CURRIER", "CUSTOM", "CUSTOM MADE", "DAIGLE", "DAKOTA", "DANCO", "DATSUN", "DAVIS", "DCTRA", "DELAVAN", "DELAWARE", "DELTA", "DELVAN", "DENAIR", "DHL", "DIAMOND", "DICO", "DIERZEN", "DINAWELD", "DIRECTTRAILER", "DITCHWITCH", "DNAIR", "DNWI", "DODGE", "DONAHUE", "DORSE", "DORSEY", "DRAGON", "DUMP TRAILER", "DUNH", "EAGER BEAVER", "EAGLE", "EAST", "ECHART", "ECHO", "ECONOLINE", "ECSA", "EMPLI", "ENCONOUR",
        "ENTYPE", "EQUIPMENT", "EZD", "FARMHAND", "FEATHERLITE", "FERRARI", "FERRE", "FIELD", "FLAT TRAILER", "FLEMMING", "FLOWBOY", "FONTAINE", "FONTANA", "FORD", "FOREST RIVER", "FOUNTAINE", "FOUR STAR TRAILER", "FREIGHTLINER", "FRUEHAUF", "G &amp; F", "GALAXY", "GALB", "GALLANTY", "GALLEGOS", "GALLITY", "GALTY", "GARWOOD", "GENERAL", "GEO", "GIBSON", "GINDY", "GLOBE", "GMC", "GMC/WHITE", "GOLDEN EAGLE", "GRACO", "GRAVE", "GREAT DANE", "GRUMMAN", "GRUMN", "GUTHERIE", "H &amp; H", "HANSON", "HARDEE", "HARDY BUILT", "HARRIS", "HART", "HAULM", "HAULMARK", "HAWKEYE", "HEACOCK", "HECHT", "HENDERSON",
        "HERITAGE", "HI-LO", "HIBILT", "HIDEBED", "HIGHSIDE", "HIGHWAY", "HILLSBORO", "HINO", "HIWAY", "HME", "HOBBS", "HOLDEN", "HOMEMADE", "HONDA", "HOPPER", "HOPRHDAT", "HULL PORTER", "HUMMER", "HYSTER", "HYUNDAI", "IEGH", "IGV", "IMC", "IMCO", "INDUSTRY", "INFINITY", "INTERNATIONAL", "INTERSTATE", "ISUZU", "IVECO", "J &amp; L", "J M",
        "JACOB", "JACOBSEN", "JAGUAR", "JAMIE/WILL", "JEEP", "JER DAN ROLL", "JET", "JOHN DEERE", "JOHNSON", "JURGI", "K &amp; H", "KALEN", "KALMAR", "KAUFMAN", "KEIL", "KENTUCKY", "KENWORTH", "KH/HH", "KIA", "KING", "KOUNTRY BOY", "KOZAD", "KW", "LAMAR", "LAMBORGHINI", "LANDOLL", "LANDROLL", "LANDROVER", "LARS", "LEXUS", "LIBER", "LID", "LIKENS", "LINCOLN", "LOAD KING", "LOAD TRAIL",
        "LOADOCK", "LOW BOY", "LOWBE", "LPLM", "LUFKIN", "MACK", "MACO", "MAGARUS", "MAGIRUS", "MANAC", "MANNI GOOSENECK", "MARMON", "MATE", "MATLOCK", "MAVRICK", "MAZDA", "MCCLAIN", "MCT", "MDL", "MERCEDES", "MERCURY", "MERRITT", "MIDLAND", "MILLER", "MINLAND", "MIRAGE", "MISCELLANEOUS", "MITSUBISHI", "MITY MOVER", "MOBIL", "MOHAWK",
        "MONON", "MORADILT", "MORGAN", "MOTAC", "MT MVR", "MURRAY", "MURRY", "MUVALL", "NABORS", "NATIONAL", "NAVISTAR", "NDMC", "NISC", "NISSAN", "NON-OWNED", "NORCAL", "NUBOIS", "NUVAN", "OLDSMOBILE", "OLYMPIAN", "ORANGE", "OTTAWA", "PACE", "PACK MULE", "PAGE", "PAIUTE", "PARAMOUNT", "PARKER", "PEERLESS", "PEGASUS", "PETERBILT", "PHE", "PIERCE", "PIKE", "PINES", "PIONEER", "PIT BOSS",
        "PITTS", "PJ", "PLYMOUTH", "PNEUM", "POLAR", "PONTIAC", "PORSCHE", "PREM", "PRFRM", "PROTRACT", "PRUDOFF", "PT WELDING", "PUP", "R-WAY", "RAM", "RANCO", "RANGEROVER", "RAVEN", "RC", "RDLN", "RED RIVER", "REINKE", "REITNOUER", "RELA", "RELIANCE", "RELIANT", "RHEA", "RIDC", "ROAD CLIPPER", "ROADMASTER", "ROBBIN", "ROBINSON", "ROGUE", "ROLLS ROYCE", "RPM",
        "SAAB", "SATURN", "SCANIA", "SCION", "SDCE", "SDI", "SEA BIRD", "SECURITY", "SHRLN", "SIDUMP", "SIEBERT", "SIERRA", "SKIPLOADER", "SMITHCO", "SNAKE RIVER", "SPATAN", "SPCNS", "SPECIAL", "SPEED KING", "SPENCER", "SPOIN", "STAR", "STECCO", "STEEL", "STERLING", "STEWART", "STOUGHTON", "STRICK", "STUART", "STUDS", "STURDYWELD", "SUBARU", "SUMMIT", "SUN COUNTRY", "SUN VALLEY", "SUNBOX", "SUNCO",
        "SUPERIOR", "SUSPENSION", "SUZUKI", "TAHOE THOR", "TAKE 3", "TALB", "TANDUM", "TANKER", "TEMPE", "TERRY", "TESCO", "TEXAS", "THEURER", "THOMPSON", "TIBROOK", "TILT TRUCK", "TIMPTE", "TITAN", "TL", "TMD", "TOASTMASTER", "TOUGHBOY", "TOWMASTER", "TOYOTA", "TRAIL BOSS", "TRAIL KING", "TRAILER", "TRAILER", "TRAILER", "TRAILEZE", "TRAILMASTER", "TRAILMAX", "TRAILMOBILE", "TRAILSTAR", "TRAMCO", "TRANANGLE", "TRANSCRAFT", "TRANSLINER", "TRANSPORT", "TRAVIS", "TRIANGLE", "TRIMELINE", "TRINITY",
        "TRIPLE CROWN", "TRISTAR", "TRIUMPH", "TRUCO", "TTC", "TUFFBOX", "TUFFBOY", "TURNBOW", "U D", "U-SAVE", "UNLIMITED", "UTCLO", "UTILITY", "VANGUARD", "VANTAGE", "VANTAR", "VEGAS", "VERSA", "VOLKSWAGEN", "VOLVO", "VULCAN", "WABASH", "WALKING FLOOR", "WALLY", "WALTON", "WARREN", "WDT", "WECO", "WEEKEND WARRIOR", "WELLS", "WELLS CARGO", "WES-TEX", "WESCO", "WESE", "WESH", "WEST-MARK", "WESTCO", "WESTERN", "WESTERN STAR", "WHITE", "WHITE-GMC", "WILDERNESS",
        "WILLIAMS", "WILLIAMSON", "WILSON", "WILX", "WINCO", "WINK", "WISCONSIN", "WITZCO", "WORKHORSE", "WRIGHT", "WW", "ZAYLE", "ZEIMAN", "ZENAN"
    ],
    'Symbol': [
        { "key": "", "value": "" },
        { "key": "Select Symbol", "value": "Select Symbol" },
        { "key": "S1", "value": "Private Passenger Auto" },
        { "key": "S2", "value": "Luxury Auto" },
        { "key": "S3", "value": "port Auto" },
        { "key": "S5", "value": "PICKUP 2X4(1 / 2 TON OR LESS)" },
        { "key": "S6", "value": "ICKUP 2X4(OVER 1 / 2 TON)" },
        { "key": "S7", "value": "ICKUP 4x4(1 / 2 TON OR LESS)" },
        { "key": "S8", "value": "ICKUP 4X4(OVER ½ TON)" },
        { "key": "S9", "value": "atering Truck" },
        { "key": "S10", "value": "Utility Vehicle" },
        { "key": "S11", "value": "Mini Van" },
        { "key": "S12", "value": "Full Size Van" },
        { "key": "S13", "value": "Step Van(GVW 0 to 10,000 lbs)" },
        { "key": "S14", "value": "Tow Truck(single axle)" },
        { "key": "S15", "value": "Car Carrier(GVW 0 to 18,000 lbs)" },
        { "key": "S20", "value": "Delivery Van(GVW 10,001 lbs and over)" },
        { "key": "S21", "value": "Straight truck(GVW 0 to 18,000 lbs)" },
        { "key": "S22", "value": "Refrigerated truck(GVW 0 to 18,000 lbs)" },
        { "key": "S23", "value": "Flatbed(GVW 0 to 18,000 lbs)" },
        { "key": "S24", "value": "Stake Body(GVW 0 to 18,000 LBS)" },
        { "key": "S25", "value": "Dump Truck(GVW 0 to 18,000 lbs)" },
        { "key": "S26", "value": "Tank Truck(1,400 gallons or less)" },
        { "key": "S27", "value": "Tow Truck(double axle)" },
        { "key": "S28", "value": "Car Carrier(GVW 18,001 &amp; over)" },
        { "key": "S29", "value": "Dump Truck(18,001 to 33,000 lbs)" },
        { "key": "S30", "value": "Straight truck(GVW 18,001 to 26,000 lbs)" },
        { "key": "S31", "value": "Refrigerated truck(GVW 18,001 to 26,000 lbs)" },
        { "key": "S32", "value": "Flatbed(GVW 18,001 to 26,000 lbs)" },
        { "key": "S33", "value": "Stake Body(GVW 18,001 to 26,000 lbs)" },
        { "key": "S34", "value": "Dump Truck(GVW 33,001 to 45,000 lbs)" },
        { "key": "S35", "value": "Tank Truck(1,401 gallons or more)" },
        { "key": "S40", "value": "Straight truck(GVW 26,001 lbs  and over)" },
        { "key": "S41", "value": "Refrigerated truck(GVW 26,001 lbs and over)" },
        { "key": "S42", "value": "Flatbed(GVW 26,001 &amp; over)" },
        { "key": "S43", "value": "Stake Body(GVW 26,001 &amp; over)" },
        { "key": "S44", "value": "Dump Truck(45,001 lbs &amp; over)" },
        { "key": "S45", "value": "Roll off Trucks" },
        { "key": "S50", "value": "Log Tractor with Trailer" },
        { "key": "S51", "value": "Log Truck with Trailer" },
        { "key": "S52", "value": "Auto Hauler Truck" },
        { "key": "S56", "value": "Tractor" },
        { "key": "S57", "value": "Pick up With 5th Wheel Hitch" },
        { "key": "S58", "value": "Agricultural Truck" },
        { "key": "S60", "value": "Dry Freight Trailer" },
        { "key": "S61", "value": "Refrigerated Trailer" },
        { "key": "S62", "value": "Flatbed Trailer" },
        { "key": "S63", "value": "Flatbed Trailer with Bunkers" },
        { "key": "S64", "value": "Tank Trailer" },
        { "key": "S65", "value": "Pole Trailer   Dump Body Trailer" },
        { "key": "S66", "value": "Livestock/ Dry Freight Trailer" },
        { "key": "S67", "value": "Low boy Trailer" },
        { "key": "S68", "value": "Tilt Trailer" },
        { "key": "S69", "value": "Bulk Commodity Trailer" },
        { "key": "S70", "value": "Rag top Trailer" },
        { "key": "S71", "value": "Auto Hauler" },
        { "key": "S72", "value": "Pneumatic Trailer" },
        { "key": "S73", "value": "Gooseneck Trailer" },
        { "key": "S74", "value": "Utility Trailer & gt; 12 ft." },
        { "key": "S75", "value": "UTILITY TRAILERS(12 FT AND UNDER)" },
        { "key": "S76", "value": "Horse Trailer" },
        { "key": "S77", "value": "Bogies and Dollies" },
        { "key": "S78", "value": "Unidentified Trailer(non owned)" },
        { "key": "S79", "value": "Non - owned end - dump or Walking Floor Trailer" },
        { "key": "S80", "value": "End Dump or Walking Floor Trailer(owned)" },
        { "key": "S81", "value": "Belly Dump Trailer" },
        { "key": "S82", "value": "Transfer Box  Trailer" },
        { "key": "S83", "value": "Pup Trailer" },
        { "key": "S84", "value": "Second Trailer hauled with another trailer at the same time" },
        { "key": "S85", "value": "Non - Owned Pneumatic Trailer" }
    ],
    'Use': [
        '', 'Commercial', 'Heavy', 'Service'
    ],
    'UMPD': [
        '', 'No Coverage', '$3,500'
    ],
    'ExcessLiabilityLimits':['','$1,000,000','$2,000,000','$3,000,000','$4,000,000','$5,000,000'],
    'ClaimantTypeCode': ['', 'First Party', 'Third Party'],
    'ConstructionType':['','Frame','Joisted Masonry','Non-Combustible','Masonry Non-Combustible','Modified Fire-Resistive','Fire-Resistive'],
        'Sprinklered':['','No','Partially Sprinklered','Fully Sprinklered'],
        'RoofType':['','Flat/Low Pitch Roof','Other Pitch - Wood','Other Pitch - Slate/Clay/Concrete','Other Pitch - Metal','Other Pitch - Other Composition/Synthetic','Builders Risk/COC'],
        'AlarmDescription':['','Local Gong','Central Station with Keys','Central Station without Keys','Police Connect'],
        'BuildingCoverage': ['', 'No', 'Yes'],
        'ProtectiveDevices': ['', 'No', 'Yes'],
        'TPCIMedPayemnts':['','$1,000','$2,500','$5,000','$10,000','Excluded'],
        'InsuredRelationship':['','Relative','Resident of Household','Employee','Insured','Other','Unknown'],
        'ClaimantType':['','First Party','Third Party'],
        'ValuationType': ['', 'Replacement Cost', 'Actual Cash Value','Functional Replacement Cost','Guaranteed Replacement Cost','Enhanced Replacement Cost'],
    'State': [
        { "key": "", "value": "" },
        { "key": "AL", "value": "Alabama" },
        { "key": "AK", "value": "Alaska" },
        { "key": "AS", "value": "American Samoa" },
        { "key": "AZ", "value": "Arizona" },
        { "key": "AR", "value": "Arkansas" },
        { "key": "AA", "value": "Armed Forces (AA)" },
        { "key": "AE", "value": "Armed Forces (AE)" },
        { "key": "AP", "value": "Armed Forces (AP)" },
        { "key": "CA", "value": "California"},
        { "key": "CO", "value": "Colorado" },
        { "key": "CT", "value": "Connecticut" },
        { "key": "DE", "value": "Delaware" },
        { "key": "DC", "value": "District of Columbia" },
        { "key": "FL", "value": "Florida" },
        { "key": "GA", "value": "Georgia" },
        { "key": "GU", "value": "Guam" },
        { "key": "HI", "value": "Hawaii" },
        { "key": "ID", "value": "Idaho" },
        { "key": "IL", "value": "Illinois" },
        { "key": "IN", "value": "Indiana" },
        { "key": "IA", "value": "Iowa" },
        { "key": "KS", "value": "Kansas" },
        { "key": "KY", "value": "Kentucky" },
        { "key": "LA", "value": "Louisiana" },
        { "key": "ME", "value": "Maine" },
        { "key": "MH", "value": "Marshall Islands" },
        { "key": "MD", "value": "Maryland" },
        { "key": "MA", "value": "Massachusetts" },
        { "key": "MI", "value": "Michigan" },
        { "key": "FM", "value": "Micronesia" },
        { "key": "MN", "value": "Minnesota" },
        { "key": "MS", "value": "Mississippi" },
        { "key": "MO", "value": "Missouri" },
        { "key": "MT", "value": "Montana" },
        { "key": "NE", "value": "Nebraska" },
        { "key": "NV", "value": "Nevada" },
        { "key": "NH", "value": "New Hampshire" },
        { "key": "NJ", "value": "New Jersey" },
        { "key": "NM", "value": "New Mexico" },
        { "key": "NY", "value": "New York" },
        { "key": "NC", "value": "North Carolina" },
        { "key": "ND", "value": "North Dakota" },
        { "key": "MP", "value": "Northern Mariana Islands" },
        { "key": "OH", "value": "Ohio" },
        { "key": "OK", "value": "Oklahoma" },
        { "key": "OR", "value": "Oregon" },
        { "key": "PW", "value": "Palau" },
        { "key": "PA", "value": "Pennsylvania" },
        { "key": "PR", "value": "Puerto Rico" },
        { "key": "RI", "value": "Rhode Island" },
        { "key": "SC", "value": "South Carolina" },
        { "key": "SD", "value": "South Dakota" },
        { "key": "TN", "value": "Tennessee" },
        { "key": "TX", "value": "Texas" },
        { "key": "UT", "value": "Utah" },
        { "key": "VT", "value": "Vermont" },
        { "key": "VI", "value": "Virgin Islands" },
        { "key": "VA", "value": "Virginia" },
        { "key": "WA", "value": "Washington" },
        { "key": "WV", "value": "West Virginia" },
        { "key": "WI", "value": "Wisconsin" },
        { "key": "WY", "value": "Wyoming" },
    ],
    'ProductType':['','Commercial Auto','Commercial Property','Commercial Excess Liability'],
    'values': ['','Auto Liability Limit', 'Employee Benefits Liability','Liquor Liability','Hired & Non-Owned'],
    'CSL':['','$1,000,000','$2,000,000'],
    'PACOL':['','$1,000,000','$2,000,000','$3,000,000','$4,000,000','Included','Excluded'],
    'GAL':['','$1,000,000','$2,000,000','$3,000,000','$4,000,000'],
    'ExcessGenAggLimit':['','$1,000,000','$2,000,000','$3,000,000','$4,000,000','$5,000,000','$6,000,000','$7,000,000','$8,000,000','$9,000,000','$10,000,000','$11,000,000','$12,000,000','$13,000,000','$14,000,000','$15,000,000','$16,000,000','$17,000,000','$18,000,000','$19,000,000','$20,000,000'],
    'ELL':['','$1,000,000','$2,000,000','$3,000,000','$4,000,000','$5,000,000'],
    'LL':['','$1,000,000','$2,000,000','Included in General Liability'],
    'PrimaryOperation': ['No', 'Yes'],
    'EachOccLimit':['','$1,000,000','$2,000,000'], 
    'ProdAndCompLimit':['','$1,000,000','$2,000,000','$3,000,000','$4,000,000','Included','Excluded'], 
    'GenAggLimit':['','$1,000,000','$2,000,000','$3,000,000','$4,000,000'],  
    'PersAdvInjLimit':['','$1,000,000','$2,000,000','$3,000,000','$4,000,000','Included','Excluded'],
    'ExcessEachOccLimit':['','$1,000,000','$2,000,000','$3,000,000','$4,000,000','$5,000,000','$6,000,000','$7,000,000','$8,000,000','$9,000,000','$10,000,000','$11,000,000','$12,000,000','$13,000,000','$14,000,000','$15,000,000','$16,000,000','$17,000,000','$18,000,000','$19,000,000','$20,000,000'],
    'RoleType':['','admin','agent'],
    'PropCoverages':['','Building Coverage','Business Personal Property','Business Income and Extra Expense','Debris Removal','Equipment Breakdown',],
    'BuildingLimits':['','$100,000','$200,000','$300,000','$400,000','$500,000'],
    'BuildingDeductible':['','$500','$1,000','$2,500','$5,000','$10,000'],
    'PropertyDeductible':['','$500','$1,000','$2,500','$5,000','$10,000'],
    'ExpandedProperty':['','Yes','No'],
    'SewerDischarge':['','Yes','No'],
    'WindHailDeductible':['','$500','$1,000','$2,500','$5,000','$10,000'],
    'PrimaryBusinessType':['','Offices','Retail','Industrial','Leisure','Healthcare'],
    'PrimaryBusinessSubType':['','Buildings','Retail - Stores','Warehouse','Bars and Restaurants','Medical Centres'],
    'BusinessYears':['','0','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','15+'],
    'ComprehensiveDeductible':['','$500','$1,000','$2,000'],
    'TowingandLabor':['','$1500','$2,000','$3,000'],
    'RentalReimbursement':['','$500','$2,500','$3,500'],
    'Model':['','Model1','Model2','Model3'],
    'RegisteredState':['','State1','State2','State3'],
    'VehicleUse':['','Business','Personal'],
    'VehicleOwnership':['','Tenants by the Entirety (Spouses)','Joint Tenants','Tenants in Common','Business Partners','Transfer on Death'],
    'MainDriverofVehicle':['','Owner','Employee','Other'],
    'NumberOfDrivers':['','2','4','6'],
    'ApiVersion':['','Exavalu_v1'],
    'groupCd': ['', '0002', '0004', '0006'],
    'agencyCd': ['', '0002-000','0002-540', '0004-000', '0004-540','0006-000', '0006-540' ]
}
