export const loss_cause_code = {
    
    'CALossCauseCode':[ '','Backing - Insured Caused','Backing - OP Caused','Cargo/Inland Marine','Collision - Insured Caused',
        'Collision - OP Caused','Collision with Fixed Object','Collision, Animal','Debris/Rock - Insured Caused','Debris/Rock - OP Caused',
        'Earthquake','Explosion','Falling Object','Fire','Flood','Glass Breakage','Injury due to Defective Condition',
        'Intersection - Insured Failed to Yield','Intersection - OP Failed to Yield','Left Turn - Insured Caused','Left Turn - OP Caused',
        'Loading and Unloading - Insured Caused','Loading and Unloading - OP Caused','Merge - Insured Caused','Merge - OP Caused',
        'Miscellaneous - APV','Mud Slide','Other Auto Accident','Parked - Insured Caused','Parked - OP Caused','Physical Damage - Other',
        'Rear End - Insured Caused','Rear End - OP Caused','Red Light - Insured Ran','Red Light - OP Ran','Right Turn - Insured Caused',
        'Right Turn - OP Caused','Rollover','Sideswipe - Insured Caused','Sideswipe - OP Caused','Stop Sign - Insured Ran',
        'Stop Sign - OP Ran','Theft - Partial','Theft - Total','Vandalism','Vehicle Jacknife','Vehicle vs. Pedestrian'
    ],
    'ExcessLossCauseCode':[ '' ,'Aircraft','Bodily Injury','Discrimination','Dog Bite','Earthquake','Environmental',
                    'False Arrest','Fire','Flood','Harassment','Liability','Libel','Malicious Prosecution','Medical Payments',
                    'Mud Slide','Other','Other Auto','Other Personal Injury','Property Damage','Slander','Slip and Fall',
                    'Terrorism','Vehicle','Wrongful Eviction','Wrongful Termination'
    ],
    'PackageLossCauseCode':[ '' ,'Advertising Injury',
                    'Atmospheric',
                    'Biological Hazards',
                    'Breach of Contract',
                    'Climatological Hazard',
                    'Collapse',
                    'Contamination',
                    'Crime - Personal',
                    'Crime - Property',
                    'Cyber',
                    'Damage Caused by Vehicles',
                    'Decay',
                    'Defects',
                    'Deterioration/Hidden or Latent Defect',
                    'Discrimination',
                    'Earthquake',
                    'Electrical Disturbance',
                    'Electrical Power Surge',
                    'Errors and Omissions',
                    'Explosion',
                    'Falling Objects',
                    'Fire',
                    'Flood',
                    'Glass Breakage',
                    'Government Actions',
                    'Harassment',
                    'Industrial Accident',
                    'Injury from Products and Operations',
                    'Leakage from Fire Protection Devices',
                    'Liquor Violation',
                    'Marring or Scratching',
                    'Mass Movement-Dry',
                    'Mass Movement-Wet',
                    'Mechanical Breakdown',
                    'Mysterious Disappearance',
                    'Neglect',
                    'Nuclear Hazard',
                    'Other',
                    'Personal Injury',
                    'Riot or Civil Commotion',
                    'Settling, Cracking, Shrinking or Expansion',
                    'Sinkhole Collapse',
                    'Storm',
                    'Terrorism',
                    'Transport-Accident',
                    'Vandalism',
                    'Volcanic Eruption',
                    'War and Military Action',
                    'Water',
                    'Wear and Tear',
                    'Wind',
                    'Workers Compensation and Similar Laws'
        ],
    'Cargo':['','Refer Breakdown','Unstable Load','Overturn or Spilled Load'],
    'Collision':['','Single Vehicle','Multiple Vehicle'],
    'Debris':['','While Towing Another Vehicle','While Not Towing Another Vehicle'],
    'Vehicle':['','Pedestrian','Bicycle','Other'],
    'Advertising':['','Intellectual Property Infringement','Other'],
    'Atmospheric':['','Dampness','Dryness','Changes in Temperature','Extremes in Temperature','Other'],
    'BiologicalHazards':['','Animal and Insect Infestation','Disease Epidemics','Other'],
    'BreachofContract':['','Failure to Perform','Fraud','Neglect','Other'],
    'ClimatologicalHazard':['','Black Ice','Cold Wave','Crop Failure','Desertification','Drought','Heat Wave','Other'],
    'Collapse':['','Building Decay','Breakage of Building Glass','Insect or Vermin Damage','Use of Defective Methods','Weight of People or Personal Property',
                'Weight of Rain that Collects on Roof','Weight of Snow, Ice or Sleet'],
    'Contamination':['','Biological','Chemical','Cross-Contamination','Physical','Other'],
    'Crime - Personal':['','Assault','Battery','False Imprisonment','Forcible Rape','Homicide','Kidnapping','Robbery','Other'],
    'Crime - Property':['','Arson','Burglary','Conversion','Embezzlement','Forgery','False Pretense','Larceny','Theft','Other'],
    'Cyber':['','Business Email Compromise','Hacker','Lost/Stolen Laptop/Device','Malware/Virus','Phishing','Ransomware','Other'],
    'Damage Caused by Vehicles':['','Road Hazard','Collision with Another Vehicle','Collision with A Fixed Object','Engine Fire','Impact with Animal','Impact with Person','Other'],
    'Decay':['','Corrosion','Dry Rot','Fungus','Mold','Rust','Wet Rot','Other'],
    'Defects':['','Design Defect','Service','Material Defect','Workmanship','Other'],
    'Deterioration/Hidden or Latent Defect':['','Hidden Decay','Improper Design','Inadequate Materials/Structures','Poor Workmanship','Other'],
    'Discrimination':['','Age','Disability','Equal Pay/Compensation','Pregnancy','Race/Color/National Origin','Religion','Sex','Other'],
    'EarthquakePkg':['','Seismic Event','Volcanic Event','Other'],
    'Electrical Disturbance':['','Electrical Circuitry Impairment','Disturbance of Electronic Data','Electrical Or Magnetic','Erasure of Electronic Data','Other'],
    'Electrical Power Surge':['','Damage or Exposed Wiring','High-Power Electrical Devices','Lightning Strikes','Overloaded Outlets or Circuits','Power Outages','Other'],
    'Errors and Omissions':['','Failure to Perform','Fraud','Negligent Act','Other'],
    'ExplosionPkg':['','Chemicals','Furnace Eruption','Gases','Rupture of Pressure Relief Devices','Steam','Water','Other'],
    'Falling Objects':['','Falling Objects','Other'],
    'FirePkg':['','Chemical Fire','Electrical Fire','Kitchen Fire','Metal Fire','Wild Brush Fire/Urban Fire','Lightning Fire','Smoke/Ash','Other'],           
    'FloodPkg':['','Dam Collapse','Flash Flood','General Flood','River Level','Underground/Sinkhole/Karst','Other'],
    'GlassBreakage':['','Glass Breakage','Other'],
    'Government Actions':['','Destruction of Property','Evacuation Order','Fire Protection','Seizure of Property','Other'],
    'Harassment':['','Creation of Hostile Environment','Libel','Retaliation','Sexual Harassment','Slander','Wrongful Termination','Other'],
    'Industrial Accident':['','Accident Release','Acid Rain','Atmosphere Pollution','Chemical Explosion','Chemical Pollution','Mine Explosion','Natural Gas Explosion','Nuclear Explosion/Radiation','Pollution','Smog','Other'],
    'Injury from Products and Operations':['','Allergic Reaction','Broken Tooth','Burns','Food Poisoning','Slip Fall','Suffocation','Trauma','Other'],
    
    'Leakage from Fire Protection Devices':['','Corrosion','Equipment Failure','Freezing','Improper Installation','Manufacturer Defect','Other'],
    'Liquor Violation':['','Over-Serving','Serving Minor','Other'],
    'Marring or Scratching':['','Marring or Scratching','Other'],
    'Mass Movement-Dry':['','Blasting','Landslide','Mass Movement','Rockfall','Subsidence - Dry','Other'], 
    'Mass Movement-Wet':['','Avalanche','Landslide/Mudslide','Subsidence - Wet','Other'], 
    'Mechanical Breakdown':['','Artificially Generated Electrical Current','Centrifugal Force Breakage','Bursting/Cracking/Splitting','Explosion','Wear and Tear','Other'], 
    'Mysterious Disappearance':['','Mysterious Disappearance','Other'], 
    'Neglect':['','Neglect','Other'],
    'Nuclear Hazard':['','Industrial Radiation Devices','Nuclear Explosion','Nuclear Power Plant Failure','Nuclear Bomb','Other'],
    'Other':['','Input in Comments Section'],
    'Personal Injury':['','Defamation/libel/Slander','Wrongful Detention','Wrongful Eviction','Other'],
    'Riot or Civil Commotion':['','Domestic Disturbance','Community Disturbance','Other'],
    'Settling, Cracking, Shrinking or Expansion':['','Settling, Cracking, Shrinking or Expansion','Other'],
    'Sinkhole Collapse':['','Sinkhole Collapse','Other'],
    'Storm':['','Freezing','Hail','Hurricane','Ice Storm','Tidal Wave','Tropical Storm','Tsunami','Water Spout','Wave Storm Surge','Other'],
    'Terrorism':['','Terrorism','Other'],
    'Transport-Accident':['','Aircraft','Boat','Motor Vehicles','Rail','Other'],
    'Vandalism':['','Graffiti','Malicious Mischief','Other'],
    'Volcanic Eruption':['','Volcanic Eruption','Other'],
    'War and Military Action':['','War and Military Action','Other'],
    'WaterPkg':['','Clogged Drain/Piping','Continuous/Repeating Seepage/Leakage of Water','Fire Abatement','Pipe Freezing','Overflow','Pipe Burst','Pipe Leakage','Other'],
    'Wear and Tear':['','Wear and Tear','Other'],
    'WindPkg':['','Cyclone','High Wind','Sand/Dust Storm','Tornado','Wind Gusts','Other'],
    'Workers Compensation and Similar Laws':['','Disease','Emotional Distress','Physical Injury','Psychological Damage','Sickness','Other']    
 
}
