export const Occupation=[
'Aggregate Haulers',
'Appliance Deliver - Residential',
'Appliance Delivery - Wholesale',
'Appliance Repair',
'Asphalt Haulers (Dry)',
'Asphalt Haulers (Wet)',
'Auto Dismantler - Junkyard ',
'Auto Haulers',
'Auto Parts Pickup',
'Bakery - Retail/Residential',
'Bakery - Wholesale',
'Blacksmiths',
'Bottled Water Delivery',
'Building Haulers',
'Building Materials Delivery',
'Building Materials Haulers',
'Canneries Packing Plants',
'Carpet Cleaners',
'Caterers',
'Caterers - Delivery',
'Common Carriers ',
'Consulting Service',
'Container Haulers (Marine or Rail)',
'Contract Hauling',
'Contractors - Paving',
'Contractors, General Trade',
'Debris Removal',
'Delivery - All',
'Delivery retail *',
'Delivery Service - Multiple Shippers',
'Delivery wholesale *',
'Demolition ',
'Department Store - Delivery',
'Equipment Dealer (non-heavy equipment)',
'Excavating',
'Exterminators - Business * Residential',
'Farm to Market - For Hire',
'Farmers - Hauls Owned Goods',
'Farmers - Occasionally Leaves  Farm',
'Fertilizer Delivery ',
'Firewood Delivery - Retail/Residential',
'Firewood Delivery - Wholesale',
'Fish and Seafood Delivery',
'Florist',
'Food Products Manufacturing',
'Frozen Food Delivery',
'Frozen Food Dist',
'Fruit Dealer',
'Furniture Delivery - Retail/Residential',
'Furniture Delivery - Wholesale',
'Furniture Repair',
'General Freight Hauler',
'Grocer - Retail/Residential',
'Grocers - Wholesale',
'Handyman/Repairman',
'Hay/Alfalfa Haulers',
'Heating and A/C Service',
'Heavy Equipment Haulers',
'Heavy Equipment Repair', 
'House Movers',
'Household Goods Movers',
'Ice Cream Vendor - Commercial',
'Installation and repair',
'Janitorial Service',
'Junk Dealers',
'Landscapers',
'Laundry Delivery - Residential Only',
'Linen Supply - Residential',
'Livestock Haulers',
'Machine Shop ',
'Mail Delivery - Rural or Suburban',
'Mail Delivery Bulk',
'Meat Dealer',
'Media Production Services',
'Metal Dealers',
'Mining Operations',
'Mobile Auto Mechanic/Detailing',
'Mobile Home Movers',
'Moving Van/Truck',
'Newspaper Delivery (Post Office to Post Office Only)',
'Outdoor Sign Installation or Placement',
'Pest Control - Business & Residential',
'Photographers',
'Printing Delivery Bulk only',
'Produce Hauler',
'Property Management',
'Quarry Operators',
'Recycled Materials Hauler',
'Rock Haulers',
'Roofer',
'Salesman',
'Sand and Gravel Haulers',
'Scrap Metal Haulers',
'Security Guards',
'Septic Tank Cleaning',
'Surveyors/Inspectors',
'Swimming Pool Cleaners',
'Tool Dealers Not Including Tool Trucks',
'Towing',
'Tree Surgeons/Trimmers (vehicles without attachments)',
'TV/Radio/VCR Repair',
'Vending Machine Delivery',
'Welders',
'Wood Chip Hauler'
]