const fileTypeMappings = {
    'Bitmap Image': 'image/bmp',
    'CSV (comma separated values)': 'application/csv',
    'GIF Image': 'image/gif',
    'HTML': 'text/html',
    'JPEG Image': 'image/jpeg',
    'MPEG Video': 'video/mpeg',
    'Microsoft Audio': 'audio/x-ms-wma',
    'Microsoft Excel Worksheet': 'application/vnd.ms-excel',
    'Microsoft Excel Worksheet (Windows 98)': 'application/x-msexcel',
    'Microsoft MODI': 'image/vnd.ms-modi',
    'Microsoft Video': 'video/x-msvideo',
    'Microsoft Word Document': 'application/msword',
    'OCTET Stream': 'application/octet-stream',
    'Open XML presentation': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'Open XML spread sheet': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'Open XML word document': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'PDF': 'application/pdf',
    'PNG Image': 'image/png',
    'Plain Text': 'text/plain',
    'Postscript': 'application/postscript',
    'Power Point': 'application/vnd.ms-powerpoint',
    'Progressive JPEG Image': 'image/pjpeg',
    'QuickTime Video': 'video/quicktime',
    'Rich Text': 'text/richtext',
    'Rich Text Format': 'application/rtf',
    'TIFF Image': 'image/tiff',
    'Wave Audio': 'audio/wav',
    'X-PNG Image': 'image/x-png',
    'XML': 'text/xml',
  };

  const statusMappings = {
    'Approved': 'approved',
    'Approving': 'approving',
    'Draft': 'draft',
    'Final': 'final',
  };

  const documentTypeMappings = {
    'Audit report': 'audit',
    'Binder': 'binder',
    'Confirmation letter': 'confirm_letter',
    'Credit report': 'credit',
    'Declination letter': 'decline_letter',
    'DecSheet': 'decsheet',
    'Diagram': 'diagram',
    'Email': 'email',
    'Email Sent': 'email_sent',
    'Inspection report': 'inspectionreport',
    'Letter received': 'letter_received',
    'Letter sent': 'letter_sent',
    'Loss history': 'loss_history',
    'Loss information': 'losses',
    'MVR': 'mvr',
    'New business application': 'newbusiness',
    'Not-Taken letter': 'not_taken_letter',
    'Other': 'other',
    'Policy summary': 'policy_summary',
    'Quote': 'quote',
    'Renewal information/instructions': 'renewalinfo',
    'Statement': 'statement',
  };
  export{
        fileTypeMappings,
        statusMappings,
        documentTypeMappings,
  };
  